name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: build
        run: npm i && npm run build
      - uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
